#!/usr/bin/env python3
"""
convert_all.py — Batch convert all thesis .md files to .typ.

Usage:
    python convert_all.py --root <path> --output-dir <typst_path>

Reads README.md for file order (fallback: alphabetical, index.md first).
Skips: AUDIT.md, FORMAT.md, PROMPT.md, README.md, FIGURES.md
"""

import re
import subprocess
import sys
import argparse
from pathlib import Path


SKIP_NAMES = {'AUDIT.md', 'FORMAT.md', 'PROMPT.md', 'README.md', 'FIGURES.md'}

SECTION_ORDER = [
    'mo-dau',
    'chuong-1',
    'chuong-2',
    'chuong-3',
    'chuong-4',
    'chuong-5',
    'ket-luan-va-huong-phat-trien',
]


def sort_key(path: Path) -> tuple:
    """Sort so that index.md comes first, then numeric-prefixed files."""
    parts = list(path.parts)
    scored = []
    for part in parts:
        if part == 'index.md':
            scored.append((0, part))
        else:
            scored.append((1, part))
    return tuple(scored)


def get_heading_shift(md_file: Path, section_dir: Path) -> int:
    """Return the heading level shift for this file.

    depth 0 (directly in section root) → shift 1  (H1 → Typst level 2)
    depth 1 index.md                   → shift 1  (index provides the section title at level 2)
    depth 1 non-index                  → shift 2  (sub-section → Typst level 3)
    depth 2+                           → shift depth+1
    """
    rel   = md_file.relative_to(section_dir)
    depth = len(rel.parts) - 1          # number of subdirectory levels
    if depth == 0 or md_file.name == 'index.md':
        return 1
    return depth + 1


def collect_section_files(section_dir: Path) -> list[Path]:
    """Return all convertible .md files in section_dir, sorted."""
    files = [
        f for f in sorted(section_dir.rglob('*.md'), key=sort_key)
        if f.name not in SKIP_NAMES
    ]
    return files


def generate_assembly(
    section: str,
    md_files: list[Path],
    luan_van_dir: Path,
    typst_dir: Path,
) -> Path:
    """Write a chapter assembly .typ that #includes all converted files."""
    if section == 'mo-dau':
        asm_path = typst_dir / 'mo-dau' / 'mo-dau.typ'
    elif section == 'ket-luan-va-huong-phat-trien':
        asm_path = typst_dir / 'ket-luan-va-huong-phat-trien' / 'ket-luan.typ'
    else:
        asm_path = typst_dir / section / f'{section}.typ'

    asm_path.parent.mkdir(parents=True, exist_ok=True)
    asm_dir = asm_path.parent

    lines = ['// Auto-generated by convert_all.py — do not edit\n\n']
    for md in md_files:
        rel_md    = md.relative_to(luan_van_dir)
        typ_path  = typst_dir / rel_md.with_suffix('.typ')
        incl_rel  = typ_path.relative_to(asm_dir)
        lines.append(f'#include "{incl_rel.as_posix()}"\n')

    asm_path.write_text(''.join(lines), encoding='utf-8')
    return asm_path


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--root',        required=True, type=Path, dest='root_dir')
    ap.add_argument('--output-dir',  required=True, type=Path, dest='output_dir')
    args = ap.parse_args()

    luan_van_dir: Path = args.root_dir.resolve()
    typst_dir:    Path = args.output_dir.resolve()
    convert_py:   Path = Path(__file__).parent / 'convert.py'

    total_ok = 0
    total_err = 0

    for section in SECTION_ORDER:
        section_dir = luan_van_dir / section
        if not section_dir.exists():
            print(f'[SKIP] {section} — directory not found')
            continue

        md_files = collect_section_files(section_dir)
        if not md_files:
            print(f'[SKIP] {section} — no .md files')
            continue

        print(f'\n[{section}] {len(md_files)} files')
        converted: list[Path] = []

        for md_file in md_files:
            rel      = md_file.relative_to(luan_van_dir)
            typ_file = typst_dir / rel.with_suffix('.typ')
            shift    = get_heading_shift(md_file, section_dir)

            result = subprocess.run(
                [sys.executable, str(convert_py),
                 '--input',       str(md_file),
                 '--output',      str(typ_file),
                 '--level-shift', str(shift)],
                capture_output=True,
            )
            stdout = result.stdout.decode('utf-8', errors='replace').strip()
            stderr = result.stderr.decode('utf-8', errors='replace').strip()
            if result.returncode != 0:
                print(f'  ERR  {rel}')
                if stderr:
                    print(f'       {stderr}')
                total_err += 1
            else:
                print(stdout)
                converted.append(md_file)
                total_ok += 1

        asm = generate_assembly(section, converted, luan_van_dir, typst_dir)
        print(f'  ASM  {asm.relative_to(typst_dir)}')

    print(f'\nDone: {total_ok} OK, {total_err} errors')


if __name__ == '__main__':
    main()
